### ISSUE TITLE
more fine-grained permission verification

### ISSUE THREAD

**Issue by quwenzhe** [yoursunny/NDNts#18]
About trust-schema module example, if authorA and authorB are both signed by adminA, authorA signed articleA, this is our expectation. Meanwhile, authorB also signed articleA, this is not our expectation. When a consumer received a data package, how to check it come from authorB, and reject it.

**Comment by yoursunny** [comment]
This question is about the design of trust schema, not the NDNts implementation.

The [trust-schema example](https://github.com/yoursunny/NDNts/blob/4a31aca8d9fe62df976a698ee6355ffe9118ad5b/packages/trust-schema/README.md) assumes these names:

* admin certificate: `/a/blog/admin/adminA/KEY/_/_/_`
* author certificate: `/a/blog/author/authorA/KEY/_/_/_`
* article: `/a/blog/article/categoryA/2023/07`

Notably, article name does not have a component that indicates author name, so that the schema cannot enforce an article can only be signed by a particular author.

If the article name is changed to `/a/blog/article/categoryA/authorA/2023/07`, it would be possible to enforce this article must be signed by authorA, with schema rules changed as follows:

```erlang
article: _site/"article"/category/authorName/year/month <= author
author: _site/"author"/authorName/_KEY <= admin
```

In this name structure, if authorB signs the packet `/a/blog/article/categoryA/authorA/2023/07`, the validator will reject the signature due to mismatched *authorName* variable.

**Comment by quwenzhe** [comment]
Thank you for your answer.  If I use the following schema rules, I want to know what's the advantage of Yingdi Yu proposed **trust schema** , compared to hierarchical trust model?

```
article: _site/"article"/category/authorName/year/month <= author
author: _site/"author"/authorName/_KEY <= admin
```

**Comment by quwenzhe** [comment]
I find hierarchical trust model proposed in 2013, Yingdi Yu's trust schema proposed in 2015, so what happened, Yingdi Yu proposed a new solution?

**Comment by yoursunny** [comment]
> what's the advantage of **trust schema** , compared to hierarchical trust model?

Hierarchical trust model is one form of trust schema.

The quoted name structure is infeasible in hierarchical trust model because author subject name is not a prefix of article name.
It is only feasible in policy trust schema that has better expressness.

**Comment by quwenzhe** [comment]
> 

I found  hierarchical trust model was proposed in 2013, Yingdi's trust schema was proposed in 2015. I want to know what happened, Yingdi propose a new solution about trust schema?

**Comment by yoursunny** [comment]
The history isn't relevant to the current implementation.
Please ask in ndn-interest mailing list instead.
If you think the history described in README requires amendment, please present the evidence.
