### ISSUE TITLE
Multiple interest sending and data retrieval

### ISSUE THREAD

**Issue by lauraalwardani** [yoursunny/NDNts#6]
with:
`data = await endpoint_sub.consume(interest);`
One interest is sent at a time and we wait for either a data packet or timeout.
I want to send multiple interests at once, and then adjust this number according to data retrieval or timeouts
In other words, we want to send the interests and handle the reply in another place.
Is it possible to split this into two separate functions, one for sending the interest and the other for handling the reply?

**Comment by yoursunny** [comment]
> send the interests and handle the reply in another place

`Endpoint#consume` returns a `Promise<Data>`, which is either resolved with the Data, or rejected upon timeout or other error condition.
You can certainly pass the Promise to handle elsewhere, instead of `await` right there.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

> send multiple interests at once, and then adjust this number according to data retrieval or timeouts

What you are referring to is similar to congestion control.
`@ndn/segmented-object` package has a congestion control algorithm that you may find useful.
