### ISSUE TITLE
SVS doesn't work with Name as ID

### ISSUE THREAD

**Issue by pulsejet** [yoursunny/NDNts#7]
The following doesn't work as expected (no updates are received), but works fine when a string is used instead of a name in `sync.add`. Is this expected?

```typescript
const sync = new SvSync({
    syncPrefix: new Name("/ndn/multicast/svs"),
    endpoint: endpoint,
})
const syncNode = sync.add(new Name(`/ndn/alice/svs`)); // <-- sync.add(`/ndn/alice/svs`) works.
```

[Reproduce on NDN Play](https://play.ndn.today/?dump=https://gist.githubusercontent.com/pulsejet/fc4671e1936ae76edb72eb4c1dc740fa/raw/4bcb6ad88d1e9565e8d096462fc0c506925d9a28/ndnts-svs-bug.json). (A,B) run a Sync group using Name and (C,D) run a separate group using string.
(running on nightly build for 10/28/2021)

**Comment by yoursunny** [comment]
[StateVectorSync Protocol Specification](https://named-data.github.io/StateVectorSync/Specification.html) version 2021-02-23 defines NodeID to be a byte array, not a name.

> NodeID = VERSION-VECTOR-KEY-TYPE TLV-LENGTH *OCTET

---

NDNts `@ndn/sync` accepts either a string or a byte array as SvSync ID.
The typing is:

```ts
class SvSync {
    get(id: IDLike): SyncNode<ID>;
    add(id: IDLike): SyncNode<ID>;
    // other members
}

type IDLike = string | Uint8Array | ID;
```

If you pass a `Name` as SvSync ID, TypeScript compiler will report a type error.
This becomes an undefined behavior if type checking is not enforced.

This design is consistent with ndn-svs C++ library, which only accepts `std::string` as ID: https://github.com/named-data/ndn-svs/blob/a5dee089253f055e553081cb202cc6da108d9d12/ndn-svs/common.hpp#L37

---

I've seen libraries using URI representation of a name when a byte array is needed:

* in PSync: https://github.com/named-data/PSync/blob/51189595bdab97ae6704407bf63f67ff7bff0ed9/PSync/producer-base.cpp#L119
* in ndn-python-svs: https://github.com/justincpresley/ndn-python-svs/blob/6aca7a62b3f74b4b2819007e1f8e2749bf58c1d3/src/ndn/svs/state_table.py#L23

This leads to [portability concerns](https://redmine.named-data.net/issues/4838) because URI representation may change over time.
Therefore, I do not follow such bad practice.

**Comment by pulsejet** [comment]
Ah, sorry my fault. The new specification of SVS will change the ID to a Name (implemented at the develop branch in the C++ lib).

Also that means I need to fix the typescript compiler in NDN Play 🤡
